################################################################################
# lime-connect
################################################################################

[[ssh-keys]]
account = "https://lime-connect.1password.com"
vault = "Employee"

[[ssh-keys]]
account = "https://lime-connect.1password.com"
item = "jeoznhsnvoum62sziz7qtogly4"

[[ssh-keys]]
account = "https://lime-connect.1password.com"
item = "2ffv35kfh3aennwms47xs2liqu"

[[ssh-keys]]
account = "https://lime-connect.1password.com"
item = "o22l7uliaylydfjgzl2taacel4"

################################################################################
# Pixel-combo
################################################################################
[[ssh-keys]]
account = "https://pixel-combo.1password.com"
vault = "Employee"

[[ssh-keys]]
account = "https://pixel-combo.1password.com"
item = "SSH-Key ssh-ed25519 (2023)"
